/* Discography data: add, remove, or edit tracks here. */
window.CS4W_TRACKS = [
  {date:'2026/06/30',name:'Aberrant Destructor',ytId:'MMoDLhNUGz4',platform:'Resurrection Cup 2026',likeId:'aberrantdestructor'},
  {date:'2023/01/02',name:'暮明',ytId:'T2Zjh2uptxI',genre:'piano',note:'PIANO SOLO',platform:'YouTube',likeId:'kureaka'},
  {date:'2021/03/06',name:'Δ5^2[n-1]14+sqrt(-1)÷',ytId:'sc-52n-114sqrt-2',source:'soundcloud',soundcloudUrl:'https://soundcloud.com/yusuke-7328/52n-114sqrt-2',thumbnail:'https://i1.sndcdn.com/artworks-y6m5xYWYyQUQyyhc-h8jZOg-t500x500.jpg',genre:'gothic-hardcore',platform:'SoundCloud',likeId:'52n114sqrt2'},
  {date:'2026/06/07',name:'Subjugator',ytId:'W9nS0Wf_PlQ',genre:'gothic-hardcore',likeId:'subjugator'},
  {date:'2026/05/25',name:'Collapse',ytId:'yRK1A5yOMJ0',genre:'midtempo',likeId:'collapse'},
  {date:'2026/04/26',name:'Aether Portal',ytId:'92ZV24CXfWo',genre:'gothic-hardcore',platform:'Myth://2.0',likeId:'aetherportal'},
  {date:'2026/04/26',name:'BACKALLEY',ytId:'GIUuHVgcSjw',genre:'bass-house',platform:'Myth://2.0',likeId:'backalley'},
  {date:'2026/04/26',name:'Synthesized Moon-ray',ytId:'RgydPti-jLY',genre:'artcore',platform:'Myth://2.0',likeId:'synthesizedmoonray'},
  {date:'2026/04/26',name:'Sacrifice feat. つぐ',ytId:'PqvP8a4ytC4',genre:'gothic',platform:'Myth://2.0',likeId:'sacrificefeat'},
  {date:'2026/04/03',name:'Risanautr',ytId:'uKN_9m-7Y4o',genre:'artcore',game:'musynx',platform:'MUSYNX:RETURN',likeId:'risanautr'},
  {date:'2025/11/15',name:'Ground Zero',ytId:'Cq4d5yBCDP4',genre:'dubstep',collab:'CS4W & Aut0',platform:'Stream Palette 6 -RANKED-',likeId:'groundzero'},
  {date:'2025/08/03',name:'AURIC INK TALISMAN',ytId:'0goAvo9qKFw',genre:'bass-house',collab:'Sylphix & CS4W',platform:'ZZZero Dripfest 2025',likeId:'auricinktalisman'},
  {date:'2025/07/11',name:'WE KNOW',ytId:'96SqTO76_t4',genre:'bass-house',collab:'feat. 冬街 緑',platform:'COLLECTIONS 401',likeId:'weknow'},
  {date:'2025/07/11',name:'Aethernix Reverie',ytId:'eDx5XRYhx18',platform:'COLLECTIONS 401',playerLabel:'COLLECTIONS 401',likeId:'aethernixreverie'},
  {date:'2025/07/11',name:'Run Free',ytId:'XF9LvmDVMwg',platform:'COLLECTIONS 401',playerLabel:'COLLECTIONS 401',likeId:'runfree'},
  {date:'2025/07/11',name:'Strange Dominator',ytId:'y0MBn5Pm-jQ',genre:'gothic-hardcore',platform:'COLLECTIONS 401',likeId:'strangedominator'},
  {date:'2025/07/11',name:'Ding Dong',ytId:'_arSudgBlpY',genre:'artcore',collab:'feat. 冬街 緑',platform:'COLLECTIONS 401',likeId:'dingdong'},
  {date:'2025/03/05',name:'Atomic Disassembler',ytId:'R2lh5Lyz888',genre:'dubstep',game:'osu',platform:'EGTS2025',likeId:'atomicdisassembler'},
  {date:'2025/02/28',name:'Stellar Pulse',ytId:'tPJd98NynHA',genre:'midtempo',collab:'VIZZEN & CS4W',platform:'CHOMPO III',likeId:'stellarpulse'},
  {date:'2025/02/23',name:'Sphalerite',ytId:'6m7wq0mdBL0',genre:'artcore',game:'orzmic',collab:'RYOQUCHA & CS4W',platform:'Orzmic / 太鼓の達人',likeId:'sphalerite'},
  {date:'2024/11/17',name:'V:Valküre',ytId:'TWenDqSDPy0',genre:'gothic-hardcore',likeId:'vvalkre'},
  {date:'2024/10/29',name:'Complementary Contrast',ytId:'b-eIFTy8DcM',genre:'artcore',platform:'Coloration',likeId:'complementarycontras'},
  {date:'2024/09/09',name:'Traxxendenza',ytId:'do-69S1inFM',genre:'gothic',game:'takumi3',platform:'TAKUMI³ / Paradigm: Reboot',note:'最優秀賞受賞',likeId:'traxxendenza'},
  {date:'2024/06/01',name:'NEO SAKURA',ytId:'dfdlU7-LxI0',genre:'artcore',collab:'RYOQUCHA & CS4W',platform:'NEURO NATION 02',likeId:'neosakura'},
  {date:'2024/01/26',name:'メイガスナイト CS4W REMIX',ytId:'hnla4xK2djE',genre:'gothic',likeId:'cs4wremix'},
  {date:'2023/12/25',name:'Evolve From Desol4tion',ytId:'uxLKfquCxco',genre:'dubstep',collab:'CS4W vs KONPEKi',likeId:'evolvefromdesol4tion'},
  {date:'2023/11/12',name:'Artemizija Irreversibility',ytId:'iHgUoohbm5k',genre:'artcore',platform:'ARTIFACTS:ASCENSIØN',likeId:'artemizijairreversib'},
  {date:'2023/08/27',name:'EX-ris',ytId:'kkE1z76fgFs',genre:'gothic-hardcore',game:'osu',platform:'Corsace Open 2023',likeId:'exris'},
  {date:'2023/07/03',name:'Hauynite',ytId:'s39x7fSSY1I',genre:'artcore',game:'dynamix lanota orzmic',collab:'RYOQUCHA & CS4W',platform:'Dynamix / Lanota / Orzmic',likeId:'hauynite'},
  {date:'2023/04/30',name:'Phoenixismia ~Hallucination of Eternity in a Timeless Realm~',ytId:'9RHykY_xA4s',genre:'artcore',game:'dynamix takumi3',collab:'C4ydora (CS4W+Pirendora)',platform:'evordeation / Dynamix',longTitle:true,likeId:'phoenixismiahallucin'},
  {date:'2023/04/24',name:'Phatchiiq',ytId:'6tL1VwTiupc',genre:'bass-house',platform:'PSYALUME',likeId:'phatchiiq'},
  {date:'2022/12/19',name:'NF:Argonaut',ytId:'74J58Lv9zno',genre:'artcore',game:'lanota',collab:'Connexio vs. CS4W',platform:'Significatio Vitae / Lanota',likeId:'nfargonaut'},
  {date:'2022/11/20',name:'Ignominiously',ytId:'acqe50irjeg',genre:'gothic-hardcore',platform:'Dystopian Arsenal',likeId:'ignominiously'},
  {date:'2022/11/13',name:'Artemizija Transfiguration',ytId:'_a32LGzqMek',genre:'artcore',platform:'ARTIFACTS:ZERØ',likeId:'artemizijatransfigur'},
  {date:'2022/08/12',name:'Circumscription',ytId:'B_BbiIyXGNg',genre:'gothic-hardcore',game:'dynamix',platform:'Dynamix',likeId:'circumscription'},
  {date:'2022/07/30',name:'Vintage Light',ytId:'wYfdL2-52TY',genre:'midtempo',likeId:'vintagelight'},
  {date:'2022/05/17',name:'V:Vallenstein',ytId:'flYWBgoP9fo',genre:'gothic-hardcore',game:'dynamix',platform:'Dynamix',likeId:'vvallenstein'},
  {date:'2022/04/24',name:'Back side of the abyss',ytId:'M00BzU8N2qY',genre:'gothic-hardcore',platform:'THE DARKEST HOUR',likeId:'backsideoftheabyss'},
  {date:'2022/03/18',name:'CX-ronos',ytId:'GeL8P1m5m1w',genre:'bass-house',game:'dancerai13 berry-melody',platform:'DanceRail3 / Berry Melody',likeId:'cxronos'},
  {date:'2021/11/28',name:'Asmodeus ~Be loyal to your desires~',ytId:'E_23LzoCLeY',genre:'gothic',collab:'Garbagecan vs. CS4W',platform:'Gloomy Goth Project',longTitle:true,likeId:'asmodeusbeloyaltoyou'},
  {date:'2021/11/01',name:'Such a Sense',ytId:'HM_ClPyGFuk',genre:'artcore',platform:'LIBEREX 002',likeId:'suchasense'},
  {date:'2021/08/15',name:'Absolute Disintegration',ytId:'9LoUBqDDYN8',genre:'gothic-hardcore',game:'takumi3',platform:'TAKUMI³',likeId:'absolutedisintegrati'},
  {date:'2021/08/13',name:'ALL',ytId:'9qrSMRc96DY',genre:'gothic',platform:'デカくなりたいコンピ',likeId:'all'},
  {date:'2021/04/09',name:'Vesper',ytId:'fmor-YxZB_U',genre:'frenchcore',likeId:'vesper'},
  {date:'2021/03/31',name:'Guilty Hostage',ytId:'yVQcZ_GgSqU',genre:'gothic-hitech',game:'dynamix',platform:'Dynamix',likeId:'guiltyhostage'},
  {date:'2020/12/29',name:'花は溺れて欣喜雀躍と',ytId:'iH3aWhMpi6Q',genre:'piano',likeId:'ih3awhmpi6q'},
  {date:'2020/12/26',name:'DainsleIV',ytId:'QK1ebO9L9OA',genre:'gothic',likeId:'dainsleiv'},
  {date:'2020/09/07',name:'Nothingnesses',ytId:'Hc3_-If0raw',genre:'ambient',likeId:'nothingnesses'},
  {date:'2020/07/25',name:'VALLEMAISON',ytId:'AZVkz-KfhJ8',genre:'gothic',likeId:'vallemaison'},
  {date:'2020/03/31',name:'Stay Ch4ngeD',ytId:'LjMXYiG2jLM',genre:'frenchcore',likeId:'staych4nged'}
];
